version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source Yarn dependencies...
      - yarn
  build:
    commands:
      - yarn build-storybook
artifacts:
  base-directory: storybook-static
  files:
    - '**/*'
  discard-paths: no
